name: Build & Publish to Cachix

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: garage
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix --experimental-features 'nix-command flakes' build .#packages.x86_64-linux.default
